services:
  #Database
  phs_db:
    image: mariadb:11.3.2
    volumes:
      - ./db_data_live:/var/lib/mysql
    ports:
      - 3322:3306
    restart: always
    env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: wordpress
    container_name: phs_db
  #Web
  phs_wp:
    depends_on:
      - phs_db
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 8081:80
    restart: always
    env_file: .env
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: phs_db
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_TABLE_PREFIX: dev_
    container_name: phs_wp
    volumes:
      - ./wp-content:/var/www/html/wp-content
  #PhpMyAdmin
  phs_myadmin:
    image: phpmyadmin:latest
    container_name: phs_myadmin
    restart: "no"
    ports:
      - 4997:80
    environment:
      PMA_HOST: phs_db
      UPLOAD_LIMIT: 100M
    depends_on:
      - phs_db
volumes:
  db_data_live:
  wp-content:
